main: me.staartvin.statz.Statz
name: Statz
version: ${project.version}
authors: [Staartvin]
description: The one-and-all plugin to record and store stats about any player.
softdepend: [Vault, Stats, Votifier, PluginLibrary]
commands:
    statz:
        description: Master command of Statz
        usage: Statz is disabled. Check your server.log!
        aliases: [stat]
permissions:
    statz.help:
        description: Allows checking the help pages
        default: true
    statz.list.self:
        description: Allows a player to check its own statistics
        default: true
    statz.list.others:
        description: Allows a player to check other players' statistics.
        default: op
    statz.hooks:
        description: Allows a player to check what plugins Statz is currently connected with
        default: op
    statz.transfer.sqlite:
        description: Allows a player to start the transferring of data from SQLite to MySQL.
        default: op
    statz.migrate:
        description: Allows a player to start migrating data from Stats 3 to Statz.
        default: op
    statz.purge:
        description: Allows a player to purge data of players
        default: op